# This is a basic workflow to help you get started with Actions

name: CI-Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
     branches: [ "integ" ]

  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
      actions: 'write'
      packages: 'write'
      pull-requests: 'write'
      
      
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0        
      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install
      # Runs a set of commands using the runners shell
      - uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.21  # E.g.: v1.21, v1.21.2, v1.21.2+k3s1
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cluster info for virtual cluster
        run: kubectl cluster-info
      - name: Setup flux on local cluster
        run: |
         cd charts
         helm install datainfra-fluxcd . -n flux --create-namespace
      - name: Check pods
        run: |
         kubectl rollout status deployment kustomize-controller -n flux
         kubectl rollout status deployment helm-controller -n flux
         kubectl rollout status deployment notification-controller -n flux
         kubectl rollout status deployment source-controller -n flux
      - name: Get Chart Version and App Version from helm 
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        id: get_chart_yaml_values
        with:
          file: charts/Chart.yaml
          appversion: appVersion
          chartversion: version
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: ${{ github.event.repository.name }}
          repository: ${{ github.repository_owner }}/stage
          tag: ${{ steps.get_chart_yaml_values.outputs.chartversion  }}-BETA
          path: charts/ # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto Merge Feature Branch -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.head_ref }}  
          target_branch: integ
          github_token: ${{ github.token }}    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: All steps passed as part of integ
          branch: integ
          base: main
        
